package com.esn.jarvis
import android.content.Context
import android.content.Intent
import android.net.Uri
object JarvisDiscordPhoneControl{
 private const val PKG="com.discord"
 private fun open(c:Context,g:String=""):Boolean=try{val i=if(g.isNotBlank())Intent(Intent.ACTION_VIEW,Uri.parse("https://discord.com/channels/"+g)).setPackage(PKG) else c.packageManager.getLaunchIntentForPackage(PKG);if(i==null)false else{i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);c.startActivity(i);true}}catch(_:Exception){false}
 fun openServer(c:Context,id:String):String{if(id.isBlank()||id.any{!it.isDigit()})return "Give me a valid Discord server ID.";c.getSharedPreferences("jarvis_discord_phone",0).edit().putString("guild_id",id).apply();return if(open(c,id))"Opening your Discord server as your logged-in account." else "I could not open Discord."}
 fun tap(c:Context,label:String)=if(!JarvisAccessibilityService.hasAccess())"Enable Phone Access for JARVIS first." else JarvisScreenInspector.tapText(label)
 fun ban(c:Context,t:String)=arm(c,"ban",t);fun kick(c:Context,t:String)=arm(c,"kick",t);fun timeout(c:Context,t:String)=arm(c,"timeout",t)
 fun mute(c:Context,t:String)=arm(c,"mute",t);fun unmute(c:Context,t:String)=arm(c,"unmute",t)
 fun deleteChannel(c:Context,t:String)=arm(c,"delete_channel",t);fun deleteMessage(c:Context,t:String)=arm(c,"delete_message",t)
 fun pin(c:Context,t:String)=arm(c,"pin",t);fun unpin(c:Context,t:String)=arm(c,"unpin",t)
 fun addRole(c:Context,t:String,role:String)=arm(c,"add_role",t,role);fun removeRole(c:Context,t:String,role:String)=arm(c,"remove_role",t,role)
 private fun arm(c:Context,a:String,t:String,x:String=""):String{if(t.isBlank())return "Tell me which Discord member, channel, or message.";c.getSharedPreferences("jarvis_discord_phone_pending",0).edit().putString("action",a).putString("target",t).putString("extra",x).putLong("until",System.currentTimeMillis()+60000).apply();open(c,c.getSharedPreferences("jarvis_discord_phone",0).getString("guild_id","").orEmpty());return "Discord "+a.replace("_"," ")+" for "+t+" is ready. Say confirm Discord action within 60 seconds."}
 fun confirm(c:Context):String{val p=c.getSharedPreferences("jarvis_discord_phone_pending",0);if(System.currentTimeMillis()>p.getLong("until",0))return "No Discord action is awaiting confirmation.";val a=p.getString("action","").orEmpty();val t=p.getString("target","").orEmpty();val x=p.getString("extra","").orEmpty();p.edit().clear().apply();if(!JarvisAccessibilityService.hasAccess())return "Enable Phone Access for JARVIS first.";if(JarvisAccessibilityService.activePackage()!=PKG)return "Discord is not the active app. Open Discord and try again.";if(t.isNotBlank()&&!JarvisScreenInspector.hasText(t))return "I cannot see "+t+" on the current Discord screen.";if(t.isNotBlank())JarvisScreenInspector.tapText(t);val labels=when(a){"ban"->arrayOf("Ban","Ban Member");"kick"->arrayOf("Kick","Kick Member");"timeout"->arrayOf("Timeout","Time Out");"mute"->arrayOf("Mute");"unmute"->arrayOf("Unmute");"delete_channel"->arrayOf("Delete Channel","Delete");"delete_message"->arrayOf("Delete Message","Delete");"pin"->arrayOf("Pin Message","Pin");"unpin"->arrayOf("Unpin Message","Unpin");"add_role","remove_role"->arrayOf("Roles","Manage Roles");else->emptyArray()};if(labels.isEmpty()||!JarvisScreenInspector.tapAny(*labels))return "I could not find that Discord control on this screen.";if((a=="add_role"||a=="remove_role")&&x.isNotBlank()&&!JarvisScreenInspector.tapAny(x))return "I reached roles but could not find "+x+".";return "Discord "+a.replace("_"," ")+" control was reached. Check the visible Discord confirmation before finalizing."}
}