#include <jni.h>
#include <string>
#include <vector>
#include <algorithm>
#include "llama.h"
struct S{llama_model* m=nullptr;llama_context* c=nullptr;};
static std::string js(JNIEnv*e,jstring v){const char*p=e->GetStringUTFChars(v,nullptr);std::string s(p?p:"");if(p)e->ReleaseStringUTFChars(v,p);return s;}
extern "C" JNIEXPORT jlong JNICALL Java_com_esn_jarvis_JarvisLlamaBackend_nativeLoad(JNIEnv*e,jobject,jstring path,jint nctx,jint nth){llama_backend_init();auto*s=new S();s->m=llama_model_load_from_file(js(e,path).c_str(),llama_model_default_params());if(!s->m){delete s;return 0;}auto p=llama_context_default_params();p.n_ctx=std::max(512,(int)nctx);p.n_batch=512;p.n_threads=std::max(1,(int)nth);p.n_threads_batch=p.n_threads;s->c=llama_init_from_model(s->m,p);if(!s->c){llama_model_free(s->m);delete s;return 0;}return reinterpret_cast<jlong>(s);}
extern "C" JNIEXPORT jstring JNICALL Java_com_esn_jarvis_JarvisLlamaBackend_nativeComplete(JNIEnv*e,jobject,jlong h,jstring pv,jint maxTok){auto*s=reinterpret_cast<S*>(h);if(!s||!s->m||!s->c)return e->NewStringUTF("");std::string p=js(e,pv);auto*v=llama_model_get_vocab(s->m);std::vector<llama_token> t(p.size()+16);int n=llama_tokenize(v,p.c_str(),p.size(),t.data(),t.size(),true,true);if(n<0){t.resize(-n);n=llama_tokenize(v,p.c_str(),p.size(),t.data(),t.size(),true,true);}if(n<=0)return e->NewStringUTF("");t.resize(n);llama_memory_clear(llama_get_memory(s->c),true);auto b=llama_batch_get_one(t.data(),t.size());if(llama_decode(s->c,b)!=0)return e->NewStringUTF("");auto sm=llama_sampler_chain_init(llama_sampler_chain_default_params());llama_sampler_chain_add(sm,llama_sampler_init_greedy());std::string out;for(int i=0;i<maxTok;i++){auto tok=llama_sampler_sample(sm,s->c,-1);if(llama_vocab_is_eog(v,tok))break;char buf[256];int z=llama_token_to_piece(v,tok,buf,sizeof(buf),0,true);if(z>0)out.append(buf,z);auto nb=llama_batch_get_one(&tok,1);if(llama_decode(s->c,nb)!=0)break;}llama_sampler_free(sm);return e->NewStringUTF(out.c_str());}
extern "C" JNIEXPORT void JNICALL Java_com_esn_jarvis_JarvisLlamaBackend_nativeFree(JNIEnv*,jobject,jlong h){auto*s=reinterpret_cast<S*>(h);if(!s)return;if(s->c)llama_free(s->c);if(s->m)llama_model_free(s->m);delete s;}